name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Python script
        run: |
          python script.py
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '483.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Verify CI-CD.yaml
        run: ls -l .github/workflows/CI-CD.yaml

      - name: Submit build
        run: gcloud builds submit --config .github/workflows/CI-CD.yaml --verbosity=debug
